import type { Project, ProjectMeta } from "../types";

export function exportProjectMetaAsString(project: Project): string {
    const {
      template_color_accent,
      template_color_background,
      template_color_box_background,
      template_box_shadow,
      template_box_border,
      template_font_family,
      template_font_size,
      template_font_weight,
      template_font_weight_heading,
      template_font_color_on_background,
      template_font_color_on_box,
      template_font_line_height,
      template_box_radius,
      form_width,
      form_custom_css,
      form_title,
      form_description,
      form_footer_text,
      form_button_text,
      form_success_message,
      form_color_light_text,
      form_color_light_text_light,
      form_color_light_accent,
      form_color_light_accent_text,
      form_color_light_input,
      form_color_light_input_text,
      form_color_dark_text,
      form_color_dark_text_light,
      form_color_dark_accent,
      form_color_dark_accent_text,
      form_color_dark_input,
      form_color_dark_input_text
    }: Project = project;
  
    const projectMeta: ProjectMeta = {
      template_color_accent,
      template_color_background,
      template_color_box_background,
      template_box_shadow,
      template_box_border,
      template_font_family,
      template_font_size,
      template_font_weight,
      template_font_weight_heading,
      template_font_color_on_background,
      template_font_color_on_box,
      template_font_line_height,
      template_box_radius,
      form_width,
      form_custom_css,
      form_title,
      form_description,
      form_footer_text,
      form_button_text,
      form_success_message,
      form_color_light_text,
      form_color_light_text_light,
      form_color_light_accent,
      form_color_light_accent_text,
      form_color_light_input,
      form_color_light_input_text,
      form_color_dark_text,
      form_color_dark_text_light,
      form_color_dark_accent,
      form_color_dark_accent_text,
      form_color_dark_input,
      form_color_dark_input_text
    };
  
    return JSON.stringify(projectMeta, null, 2);
  }
